### ISSUE TITLE
Celery worker error

### ISSUE THREAD

**Issue by slimit** [Salamek/gitlab-tools#16]
Hello,

Thank you for this great contribution.

I'm having error with the celery worker service (see the attached image), and the encryption keys could not been created.

Could you please help ?
![screenshot from 2018-07-23 21-41-15](https://user-images.githubusercontent.com/506994/43102365-d8fa271a-8ec2-11e8-9b9f-707c31ac4224.png)

**Comment by slimit** [comment]
1. We are working on a VM which do not have access to internet and there is no way to download files from it so here are print screens of the only error in the backtrace.
![screenshot from 2018-07-24 15-18-47](https://user-images.githubusercontent.com/506994/43144472-26887738-8f55-11e8-879a-4ed292dd5e4f.png)
![screenshot from 2018-07-24 15-18-19](https://user-images.githubusercontent.com/506994/43144473-26b2cc36-8f55-11e8-9a3a-24b23aa4a261.png)

2. It is on Ubuntu 16.04.4.

Thank you.

**Comment by Salamek** [comment]
@slimit was you able to solve this on your installation ? If so, pls close this issue...

**Comment by Salamek** [comment]
Ok, closing this for now, added supported Debian && Ubuntu versions in README.txt (3f6a3fa78ab2cb779e76613ba149bece77fdee29)
