### ISSUE TITLE
Support of custom SSH ports

### ISSUE THREAD

**Issue by selimb86** [Salamek/gitlab-tools#17]
Hello,

We can't use pull mirrors with custom ssh server port, could we help with that ? Any advice ?

Thank you.

**Comment by Salamek** [comment]
@slimit what URL format are you trying to use ?

**Comment by slimit** [comment]
@Salamek: ssh://git@gitlab.exemple.com:2222:some/path.git

**Comment by neyrick** [comment]
Hi, I'm confirming this issue when pushing to a remote mirror. We're using port 9222 on our legacy server for SSH, and I tried setting up a push mirror with url ssh://aaaaa@myserver.blah.com:9222/gitroot/foo/bar.git but I'm getting: 
`2:Fetching remote remote_mirror_ec60cd9741ab084076908ff172e741c8 failed: ssh: Could not resolve hostname myserver.blah.com:9222: Temporary failure in name resolution`

**Comment by Salamek** [comment]
@slimit you are using incorrect url
BAD:
```
ssh://git@gitlab.exemple.com:2222:some/path.git
```
GOOD:
```
ssh://git@gitlab.exemple.com:2222/some/path.git
```

@neyrick 
Push mirror is supported in GitLab since 10.8 version... do you have any reason to use GitlabTools push mirror functionality instead of GitLab one ?

**Comment by Salamek** [comment]
Fixed in https://github.com/Salamek/gitlab-tools/commit/ccf0fc8ffc209a5fc32535d085ec9e2d1e3af4d8
