### ISSUE TITLE
How to build this package from source code OR how to prepare an development enviorment?

### ISSUE THREAD

**Issue by rhinoceros** [Salamek/gitlab-tools#18]

**Comment by Salamek** [comment]
@rhinoceros 
I created Wiki pages for this ;-)

* https://github.com/Salamek/gitlab-tools/wiki/Command-line-options
* https://github.com/Salamek/gitlab-tools/wiki/Setting-up-development-enviorment

**Comment by rhinoceros** [comment]
That's very kind of you.

**Comment by Salamek** [comment]
Ah i provied wrong url https://github.com/Salamek/gitlab-tools/wiki/Building-distribution-package
