### ISSUE TITLE
Static files not found

### ISSUE THREAD

**Issue by andrii-trush** [Salamek/gitlab-tools#25]
Any file from directory is not found (Error 404).

Try to add to NGINX 

```
location /static {
    root /usr/lib/python3/dist-packages/gitlab_tools/static;
    gzip_static on;
    expires max;
    add_header Cache-Control public;
}
```

But still not found

**Comment by Salamek** [comment]
@andrii-trush what installation method did you used ?

**Comment by Salamek** [comment]
Closing this due to old age... reopen if issue still persists
