### ISSUE TITLE
EOF in transport thread

### ISSUE THREAD

**Issue by r1de** [Salamek/gitlab-tools#26]
Hi.  
Great work here, thank you for this tool!  
I am having an issue trying to pull mirror a github repo.  
I have successfully created a pull mirror to a gitlab repo, but github doesn't seem to work.  
gitlab-tools doesn't want to accept the github.com fingerprint.  
![github-fingerprint1](https://user-images.githubusercontent.com/4380477/63644620-fab96880-c6a1-11e9-9267-2a333616fa1c.png)  
![github-fingerprint2](https://user-images.githubusercontent.com/4380477/63644624-0147e000-c6a2-11e9-9f76-e00fce19fb26.png)  
Relevant log section:  
```
I0824 19:02:08.646 26155 log.py:282] Connected (version 2.0, client babeld-216c4091)
D0824 19:02:08.647 26155 log.py:282] kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256'] server key:['ssh-dss', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa'] client encrypt:['chacha20-poly1305@openssh.com', 'aes256-gcm@openssh.com', 'aes128-gcm@openssh.com', 'aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc'] server encrypt:['chacha20-poly1305@openssh.com', 'aes256-gcm@openssh.com', 'aes128-gcm@openssh.com', 'aes256-ctr', 'aes192-ctr', 'aes128-ctr', 'aes256-cbc', 'aes192-cbc', 'aes128-cbc'] client mac:['hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib', 'zlib@openssh.com'] server compress:['none', 'zlib', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
D0824 19:02:08.647 26155 log.py:282] Kex agreed: diffie-hellman-group-exchange-sha256
D0824 19:02:08.647 26155 log.py:282] Cipher agreed: aes128-ctr
D0824 19:02:08.647 26155 log.py:282] MAC agreed: hmac-sha2-256
D0824 19:02:08.647 26155 log.py:282] Compression agreed: none
D0824 19:02:08.879 26155 log.py:282] Got server p (2048 bits)
D0824 19:02:09.029 26155 log.py:282] kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
D0824 19:02:09.030 26155 log.py:282] Switch to new keys ...
D0824 19:02:09.031 26155 log.py:282] EOF in transport thread
I0824 19:02:09.040 26155 _internal.py:87] 10.7.151.242 - - [24/Aug/2019 19:02:09] "POST /fingerprint/fingerprint-add HTTP/1.1" 500 -
```  
Is there a way to manually add a fingerprint?  
Am I just being stupid? :)

**Comment by Salamek** [comment]
@r1de Relevant info is `10.7.151.242 - - [24/Aug/2019 19:02:09] "POST /fingerprint/fingerprint-add HTTP/1.1" 500 -`  -> Request failed with error 500
We need to know more info about this crash, is there anything in browser console ? (Request dump)
There should be full crash dump somewhere (uwsgi logs)

**Comment by r1de** [comment]
I will see what I can find and report back ASAP.  
Thankfully it is quite easy to recreate the error.  
Thank you for the response!

**Comment by r1de** [comment]
Found it.  
A simple permission issue on the /home/gitlab-tools/.ssh/known_hosts_1 file.  
perms were: `-rw-r--r-- root:root ~/.ssh/known_hosts_1`  
I am pretty sure I tried this before posting, I changed ownership of the file to `gitlab-tools:gitlab-tools` and now it works. I will watch it to see if something is changing the permissions back to root.  

Sorry for the noise. I am now not sure if this was due to something I did or not.  
You can close this issue unless you'd like more information.

73!

**Comment by Salamek** [comment]
@r1de :+1:
