### ISSUE TITLE
Documetation and Support for Building & Setting Up from Scratch

### ISSUE THREAD

**Issue by dvn0** [Salamek/gitlab-tools#30]
Thanks for this nice project. I found it via [your issue ](https://github.com/samrocketman/gitlab-mirrors/issues/105)on the `gitlab-mirrors` project. I like your improvements, but I have to say that the additional complexity is a draw back for deployment.

It's convenient that you supply pre-built packages, but I need to be able to run `gitlab-tools` from the source provided in the repo. Your build instructions are useful, but they also expect me to install your prebuilt dependencies. I have been able to work around most of this on my own, but I'm still running into issues. Would you be willing to provide some additional support/docs on setting this up from source using only either system packages (any distro) or upstream source?

**Comment by Salamek** [comment]
@dvn0 well some of those prebuild dependencies are again my projects :-D or projects that are not in distro upstream package repository... So if i want a package install to be possible,  i must provide prebuild depedencies that are missing by my self.

So if you don't trust my repository/packages there is one other ~sane option how to get this project working and that is using virtualenv + pip:

# Installation from source

1. Install venv, python3-virtualenv requirements to build a pycrypto

```sh
apt update
apt install virtualenv python3-virtualenv build-essential python3-dev
```

2. Clone this repo

```sh
git clone https://github.com/Salamek/gitlab-tools.git
```

3. Create virtualenv in same dir where repo clone is

```sh
virtualenv -p python3 gitlab-tools/venv
```

4 . Activate virtualenv
```sh
cd gitlab-tools
source venv/bin/activate
```

5. Install depedencies ("requirements"), these are installed from Python Package Index (https://pypi.org/)
```sh
pip3 install -r requirements.txt
```

6. Run gitlab-tools CLI (it is same as running `gitlab-tools` when installed using prebuild package) from here you can continue with the setup mentioned in README.txt
```sh
python3 manage.py <command>
```


(If you don't want to use pip to install depedencies, you can also clone all depedencies from their upstream git / .tar.gz  etc. and extract them [python packages not repo folders] next to the gitlab_tools folder [inside gitlab-tools folder] but that would be kinda crazy :P and it will give me a PTSD lol)

**Comment by dvn0** [comment]
Thanks for the instructions. This look similar to what's in the wiki, which I tried already. Had some problems in the end, but I'll have to follow up on that later. I'll open another issue if I can reproduce the problem.
