### ISSUE TITLE
Repository names are not correct

### ISSUE THREAD

**Issue by cenk1cenk2** [Salamek/gitlab-tools#36]
Hey again @Salamek ,

I just wonder now with the latest additions I have encountered two issues:

- One of them is very fatal and it modifies the git URLs with the user id, I am not sure if this was the behavior before, so I am not a hundred percent confident that this is the actual error.

The error message is: `Error lines received while fetching: error: failed to push some refs to 'gitlab.kilic.dev_1:libraries/cz-cc.git'`

My debugging output:
```sh
root@bb31e0793154:/home/service/repositories/1/pull/2/7# git pull --mirror
fatal: this operation must be run in a work tree
root@bb31e0793154:/home/service/repositories/1/pull/2/7# cd ..
root@bb31e0793154:/home/service/repositories/1/pull/2# ls
2  7
root@bb31e0793154:/home/service/repositories/1/pull/2# git ^C
root@bb31e0793154:/home/service/repositories/1/pull/2# cd 7
root@bb31e0793154:/home/service/repositories/1/pull/2/7# git remote show origin
ssh: Could not resolve hostname github.com_1: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@bb31e0793154:/home/service/repositories/1/pull/2/7# git remote show gitlab
ssh: Could not resolve hostname gitlab.kilic.dev_1: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
root@bb31e0793154:/home/service/repositories/1/pull/2/7#

```

- The other one is that it does not auto check the form options from the Advanced Options anymore, therefore it changes the options every time the repository is edited unless it is been done manually.

What can I do to help with these issues?

These do not show inside the frontend task logs as errors but on the stdoutput of the application.

**Comment by Salamek** [comment]
@cenk1cenk2 

> One of them is very fatal and it modifies the git URLs with the user id, I am not sure if this was the behavior before, so I am not a hundred percent confident that this is the actual error.


modified hostname in URL is fine, it is used as a "identifier" for sections in '~/.ssh/config' where correct hostname + correct public key is specified...
so you **have** to run those commands as `gitlab-tools` user for it to work correctly (you are running it as `root`)

> The other one is that it does not auto check the form options from the Advanced Options anymore, therefore it changes the options every time the repository is edited unless it is been done manually.

Hmm looks like config is not saved/loaded correctly from DB, i need to check this...

**Comment by cenk1cenk2** [comment]
Oh yeah, that is nonsense whenever I run it with a service user now it works fine.

So I guess this one comes from some place else:
`[worker] W0418 17:23:39.260 4414 remote.py:821] Error lines received while fetching: error: failed to push some refs to 'gitlab.kilic.dev_1:libraries/cz-cc.git'`

**Comment by Salamek** [comment]
Maybe temporary network error?

**Comment by cenk1cenk2** [comment]
Hmm, that would make sense ofc. I will try to debug this further. Thank you very much for your time.

**Comment by Salamek** [comment]
@cenk1cenk2 That not filled checkbox when editing should be fixed in 1.2.6

**Comment by cenk1cenk2** [comment]
Cool, thank you very much and I have done further debugging for the other issue. It seems the network connection between the servers are fine and the SSH request seem to propagate but it is still complaining about not being able to push.

**Comment by Salamek** [comment]
Hmm try to simulate same commands that gitlab-tools are calling when doing sync, all tasks are in `gitlab_tools/tasks/gitlab_tools.py`

* save_pull_mirror is called when pull_mirror form is saved
* sync_pull_mirror is called when sync is triggered by clicking "Trigger sync" button or by HTTP hook or by cron

So depending on in what stage it is crashing for you check the code in corresponding task

**Comment by cenk1cenk2** [comment]
Hey @Salamek ,
I guess this issue was related to having messed up the the db advanced options section, when I selected enable pruning mirrors, all is fine now.

Again I would like to thank you again on writing this very useful tool as well as taking the time maintain it yet again.
