### ISSUE TITLE
repository.salamek.cz is not available

### ISSUE THREAD

**Issue by Findus23** [Salamek/gitlab-tools#41]
Hi,

Thanks for your great tool. 
Maybe I just have a bad timing, but `https://repository.salamek.cz/` doesn't seem to be reachable for me.
```
➜  ~ curl -v https://repository.salamek.cz/
*   Trying 78.80.161.207:443...
* connect to 78.80.161.207 port 443 failed: No route to host
* Failed to connect to repository.salamek.cz port 443 after 895 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to repository.salamek.cz port 443 after 895 ms: Couldn't connect to server

**Comment by Salamek** [comment]
Yea, i was on vacation and one of my servers just kernel paniced ... should be running now but it may crash again (i need to investigate what is going on)
