### ISSUE TITLE
gitlab-tools-bgtask has crashed

### ISSUE THREAD

**Issue by ericxliu1990** [Salamek/gitlab-tools#43]
I run into the following failure with the "cenk1cenk2/gitlab-tools" docker image. Please let me know what you need to debug this issue further. 
> [START] Starting the celerybeat...
[bgtask] celery beat v5.0.2 (singularity) is starting.
[bgtask] __    -    ... __   -        _
[bgtask] LocalTime -> 2023-01-02 19:15:58
[bgtask] Configuration ->
[bgtask]     . broker -> amqp://guest:**@127.0.0.1:5672//
[bgtask]     . loader -> celery.loaders.app.AppLoader
[bgtask]     . scheduler -> gitlab_tools.celery_beat.schedulers.DatabaseScheduler
[bgtask]
[bgtask]     . logfile -> [stderr]@%WARNING
[bgtask]     . maxinterval -> 5.00 seconds (5s)
[bgtask] F0102 19:15:59.032 195392 beat.py:107] beat raised exception <class 'AttributeError'>: AttributeError("'NoneType' object has no attribute 'now'")
[bgtask] Traceback (most recent call last):
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/apps/beat.py", line 105, in start_scheduler
[bgtask]     service.start()
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 618, in start
[bgtask]     humanize_seconds(self.scheduler.max_interval))
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/kombu/utils/objects.py", line 30, in __get__
[bgtask]     return super().__get__(instance, owner)
[bgtask]   File "/usr/lib/python3.9/functools.py", line 969, in __get__
[bgtask]     val = self.func(instance)
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 662, in scheduler
[bgtask]     return self.get_scheduler()
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 653, in get_scheduler
[bgtask]     return symbol_by_name(self.scheduler_cls, aliases=aliases)(
[bgtask]   File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 144, in __init__
[bgtask]     super().__init__(*args, **kwargs)
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 253, in __init__
[bgtask]     self.setup_schedule()
[bgtask]   File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 150, in setup_schedule
[bgtask]     self.install_default_entries(self.schedule)
[bgtask]   File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 225, in schedule
[bgtask]     self._schedule = self.all_as_schedule()
[bgtask]   File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 158, in all_as_schedule
[bgtask]     s[model.name] = self.Entry(model)
[bgtask]   File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 34, in __init__
[bgtask]     super().__init__()
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 124, in __init__
[bgtask]     self.last_run_at = last_run_at or self.default_now()
[bgtask]   File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 128, in default_now
[bgtask]     return self.schedule.now() if self.schedule else self.app.now()
[bgtask] AttributeError: 'NoneType' object has no attribute 'now'
[bgtask] W0102 19:15:59.034 195392 log.py:227] Traceback (most recent call last):
[bgtask] W0102 19:15:59.034 195392 log.py:227] File "/opt/gitlab-tools/manage.py", line 7, in <module>
[bgtask] W0102 19:15:59.034 195392 log.py:227] main()
[bgtask] W0102 19:15:59.034 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/bin/gitlab_tools.py", line 572, in main
[bgtask] W0102 19:15:59.034 195392 log.py:227] getattr(command, 'chosen')()  # Execute the function specified by the user.
[bgtask] W0102 19:15:59.034 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/bin/gitlab_tools.py", line 534, in celerybeat
[bgtask] W0102 19:15:59.035 195392 log.py:227] return celery.Beat(
[bgtask] W0102 19:15:59.035 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/apps/beat.py", line 77, in run
[bgtask] W0102 19:15:59.035 195392 log.py:227] self.start_scheduler()
[bgtask] W0102 19:15:59.035 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/apps/beat.py", line 105, in start_scheduler
[bgtask] W0102 19:15:59.035 195392 log.py:227] service.start()
[bgtask] W0102 19:15:59.035 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 618, in start
[bgtask] W0102 19:15:59.036 195392 log.py:227] humanize_seconds(self.scheduler.max_interval))
[bgtask] W0102 19:15:59.036 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/kombu/utils/objects.py", line 30, in __get__
[bgtask] W0102 19:15:59.036 195392 log.py:227] return super().__get__(instance, owner)
[bgtask] W0102 19:15:59.036 195392 log.py:227] File "/usr/lib/python3.9/functools.py", line 969, in __get__
[bgtask] W0102 19:15:59.036 195392 log.py:227] val = self.func(instance)
[bgtask] W0102 19:15:59.036 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 662, in scheduler
[bgtask] W0102 19:15:59.037 195392 log.py:227] return self.get_scheduler()
[bgtask] W0102 19:15:59.037 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 653, in get_scheduler
[bgtask] W0102 19:15:59.037 195392 log.py:227] return symbol_by_name(self.scheduler_cls, aliases=aliases)(
[bgtask] W0102 19:15:59.037 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 144, in __init__
[bgtask] W0102 19:15:59.037 195392 log.py:227] super().__init__(*args, **kwargs)
[bgtask] W0102 19:15:59.037 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 253, in __init__
[bgtask] W0102 19:15:59.037 195392 log.py:227] self.setup_schedule()
[bgtask] W0102 19:15:59.038 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 150, in setup_schedule
[bgtask] W0102 19:15:59.038 195392 log.py:227] self.install_default_entries(self.schedule)
[bgtask] W0102 19:15:59.038 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 225, in schedule
[bgtask] W0102 19:15:59.038 195392 log.py:227] self._schedule = self.all_as_schedule()
[bgtask] W0102 19:15:59.038 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 158, in all_as_schedule
[bgtask] W0102 19:15:59.038 195392 log.py:227] s[model.name] = self.Entry(model)
[bgtask] W0102 19:15:59.038 195392 log.py:227] File "/opt/gitlab-tools/gitlab_tools/celery_beat/schedulers.py", line 34, in __init__
[bgtask] W0102 19:15:59.038 195392 log.py:227] super().__init__()
[bgtask] W0102 19:15:59.038 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 124, in __init__
[bgtask] W0102 19:15:59.038 195392 log.py:227] self.last_run_at = last_run_at or self.default_now()
[bgtask] W0102 19:15:59.038 195392 log.py:227] File "/opt/gitlab-tools/venv/lib/python3.9/site-packages/celery/beat.py", line 128, in default_now
[bgtask] W0102 19:15:59.038 195392 log.py:227] return self.schedule.now() if self.schedule else self.app.now()
[bgtask] W0102 19:15:59.038 195392 log.py:227] AttributeError
[bgtask] W0102 19:15:59.038 195392 log.py:227] :
[bgtask] W0102 19:15:59.038 195392 log.py:227] 'NoneType' object has no attribute 'now'

**Comment by Salamek** [comment]
Shoud be fixed in gitlab-tools  1.4.4
