### ISSUE TITLE
Support provisioning via docker-compose

### ISSUE THREAD

**Issue by samrocketman** [Salamek/gitlab-tools#5]
It would be nice if an example of running this service was available for running via `docker-compose`.  Mainly because this seems to have a lot of moving parts and if one wanted to get set up quickly, docker-compose would be easiest from a systems perspective.

**Comment by Salamek** [comment]
https://docs.docker.com/compose/django/#define-the-project-components looks like good point to start

**Comment by BallisticPain** [comment]
I think this is a good idea to have... also some instructions on Kubernetes and how to go about setting it up that way too.

**Comment by Salamek** [comment]
Anyone willing to help with this ? It will take some time till i have time to work on this...

**Comment by JBou** [comment]
Is there a way to make this happen? I would love to use it, but without a docker container i can't.

**Comment by cenk1cenk2** [comment]
I have given a fair amount of tries for this. But the dependencies seem out of date and I just can not find the right combination of dependencies with the correct Debian version.

As I have understood it, correct me if I am wrong the URL variables of Redis and RabbitMQ are also hardcoded. If it was available through docker config, that would also improve the packaging process.

**Comment by Salamek** [comment]
This should be solved by #34 && https://github.com/cenk1cenk2/docker-gitlab-tools/blob/main/README.md
