### ISSUE TITLE
Request failed error while adding a fingerprint

### ISSUE THREAD

**Issue by debugger89** [Salamek/gitlab-tools#7]
I started to use this tool for using the gitlab pull mirrors. 
I installed the tool using the suggested apt-get installation as given in the readme. GitLab and the tools are installed in the same linux (ubuntu 16.4) machine.
The logging in to GitLab Tools page is working fine and login gitlab authorization is working as expected.
![image](https://user-images.githubusercontent.com/6268682/41414534-f107d146-7003-11e8-88ab-3d3e505f8308.png)

Here is my fingerprints screen

![image](https://user-images.githubusercontent.com/6268682/41414565-0b615256-7004-11e8-8ffd-cfefdc96666b.png)

I have configured an SSH key for my GitLab account and it is working.

**Issue :** 

While trying to create a pull mirror following are my settings. 
![image](https://user-images.githubusercontent.com/6268682/41414814-ad11874c-7004-11e8-822c-7b6ba0cb0bd4.png)
And upon saving following error occures. 

![image](https://user-images.githubusercontent.com/6268682/41414904-e0ed869c-7004-11e8-8d42-65f3b7181fae.png)

Attched the server log

[gitlab-tools_server.log](https://github.com/Salamek/gitlab-tools/files/2102512/gitlab-tools_server.log)

**Comment by debugger89** [comment]
@Salamek appreciate your help on this

**Comment by debugger89** [comment]
I am getting the same error while trying to add a fingerprint from the from the fingerprint screen. Actually adding fingerprint is not coverted in Wiki. If you can describe them im more than willing to contribute to the wiki. :)

**Comment by Salamek** [comment]
@debugger89 will fix ASAP ~ +1hour

**Comment by debugger89** [comment]
Thanks a lot for fixing this. You are awsome

**Comment by Salamek** [comment]
@debugger89 it is out, you may test it
