### ISSUE TITLE
Pull mirroring does not work for existing repository

### ISSUE THREAD

**Issue by debugger89** [Salamek/gitlab-tools#8]
If the mirror and the mirrored both repos existing in the gitlab there is no way to setup mirroring between them. 

Use case:
For syncing fork repositories and their upstream repo, the tool is not supporting the sync. 

Expected behavior:

The tool should be able to setup sync between the two existing repos (fork and original)
And the pull sync should have the merging capabilities for the fork repo

**Comment by Salamek** [comment]
@debugger89 Can you pls write down how to reproduce this ?

**Comment by debugger89** [comment]
Issue reproduce steps:

Create a project in a gitlab group as below.

Group name: Group1
Project name: ProjectMaster

Fork the ProjectMaster project using the fork button in the GitLab ui. 

Now try to create a pull mirror in the tool for the two projects. Give the original ProjectMaster git repo ssh url and the the forked project name as inputs for the pull mirror. 

Expected behavior:

The fork repository should be merged with the upstream and synced. (As if using git merge upstream/master and pushing the merge to origin/master)


Actual behavior:

No merge nor mirroring happen between the two repositories. And also the trigger sync button is disappearing from the pull mirror screen

**Comment by debugger89** [comment]
@Salamek but as far as i can see this does not fix the original issue of merging the two projects. This doe the mirroring. But acts as a force push for the mirror project?
Awsome work btw

**Comment by debugger89** [comment]
So this issue is **not** officially closed :)

**Comment by debugger89** [comment]
@Salamek I tested the solution, but the mirroring is not happening between the forked repositories yet.
Trigger sync button is available in the pull mirror screen though. 
I'm sorry but this issue is not resolved.

**Comment by Salamek** [comment]
@debugger89 well mirroring and merging are two differend things... and only mirroring is supported now.
But i may add differend mirror strategies like:
* Git mirror (fetch -> push --mirror)
* Git merge (fetch -> merge -> push, only master branch, mirror will fail on merge conflict)

Reopening issue + changing from bug to enhancement

**Comment by debugger89** [comment]
Mirror failure should be visible to the user in the UI level in order to understand the issue.

Any ETA on this?

**Comment by Salamek** [comment]
@debugger89 This depends on #1 and that depends on solving https://github.com/Robpol86/Flask-Celery-Helper/pull/22 ...
I will try to look on it today

**Comment by Salamek** [comment]
This should be ~solved by #1 i think? Closing...
